# -*- coding: utf-8 -*-
# HTML template
_html = {
    'page-top': """<html><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Analysis Report</title>
    </head><body id="page-top">
    <style>{}</style>
    <svg class="d-none">
        <defs>
            <path id="narrow" style="text-align:start;line-height:100%;-inkscape-font-specification:Arial Unicode MS" d="M24.35 7.613c-3.035 1.11-5.407 2.908-7.113 5.395h-1.299c.585-1.743 1.567-3.39 2.945-4.938H.649V6.278h18.234c-1.378-1.548-2.36-3.2-2.945-4.956h1.299c1.706 2.487 4.078 4.285 7.114 5.395v.896z" font-size="39.506" font-weight="400" font-family="Arial Unicode MS"/>
        </defs>
    </svg>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">ReacNetGenerator</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#network">Network</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#species">Species</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#reactions">Reactions</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <header class="masthead text-center text-white d-flex bg-dark imgbg" id="info">
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <h1 class="text-uppercase">Analysis Report</h1>
                </div>
                <div class="col-lg-10 mx-auto">
                    <p><strong>Please cite:</strong> J. Zeng, L. Cao, J.Z.H. Zhang, C.-H. Chen, T. Zhu: ReacNetGen: an Automatic Reaction Network Generator for Reactive Molecular Dynamic Simulations, 2018, doi:<a href="https://dx.doi.org/10.26434/chemrxiv.7421534">10.26434/chemrxiv.7421534</a></p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 mx-auto text-center">
                    <div class="service-box mt-5 mx-auto">
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="#network">Network</a>
                    </div>
                </div>
                <div class="col-lg-3 mx-auto text-center">
                    <div class="service-box mt-5 mx-auto">
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="#species">Species</a>
                    </div>
                </div>
                <div class="col-lg-3 mx-auto text-center">
                    <div class="service-box mt-5 mx-auto">
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="#reactions">Reactions</a>
                    </div>
                </div>
            </div>
        </div>
    </header>""",
    'bk-css': """.spec{height:100px;width:100px;}.content-table{font-size:14;margin-left:auto;margin-right:auto;text-align:center;}.reacnum{color:blue;}.specnone,.reacnone{display:none;}#info{background-image:url(%s)}""",
    'page-bottom': """<section class="bg-dark text-white" id="foot">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <p>Generated by <a href="https://njzjz.github.io/reacnetgenerator">ReacNetGenerator</a></p>
            <p><strong>Citation:</strong> J. Zeng, L. Cao, J.Z.H. Zhang, C.-H. Chin, T. Zhu: ReacNetGen: an Automatic Reaction Network Generator for Reactive Molecular Dynamic Simulations, 2018, doi:<a href="https://dx.doi.org/10.26434/chemrxiv.7421534">10.26434/chemrxiv.7421534</a></p>
            <p><strong>Author:</strong> <a href="https://cv.njzjz.win/">Jinzhe Zeng</a>, Liqun Cao, <a href="https://research.shanghai.nyu.edu/centers-and-institutes/chemistry/people/john-zenghui-zhang">John ZH Zhang</a>, Chih-Hao Chin, <a href="http://computchem.cn/people/">Tong Zhu</a></p>
            <p><strong>Email:</strong> <a href="mailto:tzhu@lps.ecnu.edu.cn">tzhu@lps.ecnu.edu.cn</a>, <a href="mailto:jzzeng@stu.ecnu.edu.cn">jzzeng@stu.ecnu.edu.cn</a></p>
          </div>
        </div>
      </div>
    </section>
    <script>{}</script>
    </body></html>""",
    'network': """<section id="network" class='bg-white mx-auto text-center'>
        <div class="container my-auto">
            <div class="row">
                <div class="mx-auto w-100 text-center">
                    <h2>Reaction Network</h2>
                    %s
                </div>
            </div>
        </div>
    </section>""",
    'species-top': """<section id="species" class='bg-white mx-auto'>
    <div class="container">
        <div class="row">
            <div class="mx-auto text-center">
                <h2 class='text-center'>Species</h2>
                <table class='content-table'>""",
    'species-each': """%s<td><svg class='spec'><use xlink:href="#%s"></use></svg><br/>%s</td>%s""",
    'species-bottom': """</table>
            </div>
            <div class="mx-auto text-center mt-5">
                <a class="btn btn-primary btn-xl js-scroll-trigger" href="javascript:$('.specnone').show();$('#showmorespec').hide();" id="showmorespec">Show all</a>
            </div>
        </div>
    </section>""",
    'reactions-top': """<section id="reactions" class='bg-white mx-auto'>
    <div class="container">
        <div class="row">
            <div class="mx-auto text-center">
                <h2 class='text-center'>Reactions</h2>
                <h4 class='text-center'>(sorted by frequency)</h4>
                <table class='content-table'>""",
    'reactions-each': """%s<td>%s</td><td><svg class='spec'><use xlink:href="#%s"></use></svg></td>
    <td class="reacnum">%s<br/>%s</td>
    <td><svg class='spec'><use xlink:href="#%s"></use></svg></td>
    %s""",
    'reactions-bottom': """</table>
            </div>
            <div class="mx-auto text-center mt-5">
                <a class="btn btn-primary btn-xl js-scroll-trigger" href="javascript:$('.reacnone').show();$('#showmorereac').hide();" id="showmorereac">Show all</a>
            </div>
        </div>
    </section>""",
    'narrowurl': '''<svg width="25" height="14.33"><use xlink:href="#narrow"/></svg>''',
    'speciessvg-top': '''<svg class="d-none"><defs>''',
    'speciessvg-each': '''<svg id="%s">%s</svg>''',
    'speciessvg-bottom': '''</defs></svg>''',
    'script-hidereac': '''$('#showmorereac').hide();''',
    'script-hidespec': '''$('#showmorespec').hide();''',
    'tr-top':'''<tr>''',
    'tr-specnone':'''<tr class='specnone'>''',
    'tr-reacnone':'''<tr class='reacnone'>''',
    'tr-bottom':'''</tr>''',
}
