on: [push, pull_request]
name: Release to pypi
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64
    - run: pip install pep517
    - run: python -m pep517.build .
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
